### ISSUE TITLE
[FEAT] 책 목록 조회

### ISSUE THREAD

**Issue by bbabbi** [NOWSOPT-CDSP-WEB-1/Brunch-Web-Server#4]
## 📌 구현하려고 하는 것

책 정보를 다루는 총 4개의 API를 구현합니다.
- 최근 읽은 책 정보 조회 API
- 책 상세 조회 API
- 배너 조회 API
- 책 좋아요 API

### 1️⃣ 최근 읽었던 책 목록 조회

**[최근 읽었던 책 목록]**

![recentBooks](https://github.com/NOWSOPT-CDSP-WEB-1/Brunch-Web-Server/assets/84909012/9f1b3e58-14a3-4944-a862-f88851e97b45)

**[라이킷한 책 목록]**

![LikedBooks](https://github.com/NOWSOPT-CDSP-WEB-1/Brunch-Web-Server/assets/84909012/99e9cd55-219f-4400-986a-c49206291024)

### 2️⃣ 책 상세 조회

<img width="769" alt="스크린샷 2024-05-16 오후 5 08 33" src="https://github.com/NOWSOPT-CDSP-WEB-1/Brunch-Web-Server/assets/84909012/98fcfd5e-8df3-468a-b87a-7cb563af7591">

### 3️⃣ 배너 조회

<img width="763" alt="스크린샷 2024-05-17 오후 1 03 18" src="https://github.com/NOWSOPT-CDSP-WEB-1/Brunch-Web-Server/assets/84909012/0e994ac7-8c0a-47c4-af76-e0a453e8a96a">

### 4️⃣ 책 좋아요

<img width="784" alt="스크린샷 2024-05-17 오후 2 16 44" src="https://github.com/NOWSOPT-CDSP-WEB-1/Brunch-Web-Server/assets/84909012/6ec67885-6ca9-41a1-8df2-6b228fa28b6a">

## ✅ Tasks
- [x] 최근 읽은 책 정보 API (/api/v1/books)
- [x] 책 상세 정보 API (/api/v1/books/{bookId})
- [x] 배너 조회 API (/api/v1/books/banner)
- [x] 책 좋아요 API(/api/v1/books/{bookId}/likes)
